# Generated by Django 3.1.2 on 2021-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_auto_20210702_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
